# Docs for Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dayplanner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies, build, and test
        run: |
          cd client
          npm install
          npm run build --if-present || { echo "Build failed"; exit 1; }
          npm run test --if-present

      - name: Debug - List files after build
        run: |
          cd client
          ls -la

      - name: Zip artifact for deployment
        run: |
          cd client
          if [ -d "build" ]; then
            zip -r ../release.zip build
          elif [ -d ".next" ]; then
            zip -r ../release.zip .next
          elif [ -d "dist" ]; then
            zip -r ../release.zip dist
          else
            echo "No valid build output found! Check the build process."
            exit 1
          fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read  # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AB7546091F1F408CAE9239F979AD4E2C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8274BD6BCB2F481C9761D229D67F2B89 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_20754DB68A954298885EC6F6CC1EEF1A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dayplanner'
          slot-name: 'Production'
          package: build
