name: Build and deploy Node.js app to Azure Web App - dayplanner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install pnpm
        run: |
          npm install -g pnpm  # Install pnpm globally

      - name: Install dependencies and build API
        run: |
          cd api  # Navigate to the /api folder
          pnpm install  # Use pnpm to install dependencies
          pnpm run build --if-present  # Use pnpm to build
          pnpm run test --if-present  # Use pnpm to run tests

      - name: Zip artifact for deployment
        run: |
          cd api  # Navigate to the /api folder
          zip -r ../release.zip ./*  # Zip the contents of /api folder

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_028DE1A2E627486AB5D8494B8659486F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4AFF1D1721BB4081809B4FB733AFBA8B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_22AA7F93F4684E0891C5BA0A3C18B14D }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dayplanner'
          slot-name: 'Production'
          package: "./api"  # Ensure the correct folder is deployed
